### ISSUE TITLE
Searching for a good way of testing with jspm

### ISSUE THREAD

**Issue by fernandogmar** [jackfranklin/jspm-test#1]
Hi Jack,

I have more or less the same problem that you had when you created this project, I am guessing if you found other ways to do these tests because it seems you haven't touched this project in 2 years....

before Systemjs/Jspm I was using a lot requirejs, for that time I remember a really nice test-framework [testem](https://github.com/testem/testem) , no idea how it is the status nowadays…

for now I have found
[https://github.com/OrKoN/jspm-testem](https://github.com/OrKoN/jspm-testem)
[https://medium.com/@capajj/why-it-is-foolish-to-use-karma-with-jspm-3af9ebd02af](https://medium.com/@capajj/why-it-is-foolish-to-use-karma-with-jspm-3af9ebd02af)

I am trying to find more recent opinions about how to do test across different browsers smoothly with jspm,

Thanks in advance!

**Comment by jackfranklin** [comment]
Heya,

As you guessed this isn't something I'm working on any more - I unfortunately don't work with jspm much these days and therefore I couldn't help you here. Feel free to take any of this code and run with it but I can't offer any insight unfortunately.
